force-app/main/default/objects/Account/fields/Facebook__c.field-meta.xml
<CustomField>
    <fullName>Facebook__c</fullName>
    <label>Facebook</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <label>Meetup</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Club__c.field-meta.xml
<CustomField>
    <fullName>Club__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Club</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>ClubSchedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/MeetingDate__c.field-meta.xml
<CustomField>
    <fullName>MeetingDate__c</fullName>
    <label>Meeting Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MeetingAgendaController.cls
public with sharing class MeetingAgendaController {
    @TestVisible
    private static Boolean isMeetingDateAccessible {
        get {
            if (isMeetingDateAccessible == null) {
                isMeetingDateAccessible =
                    Schema.SObjectType.Schedule__c.isAccessible() &&
                    Schedule__c.MeetingDate__c.getDescribe().isAccessible();
            }
            return isMeetingDateAccessible;
        }
        set;
    }

    @TestVisible
    private static Boolean isAccountAccessible {
        get {
            if (isAccountAccessible == null) {
                isAccountAccessible = Schema.SObjectType.Account.isAccessible();
            }
            return isAccountAccessible;
        }
        set;
    }

    @AuraEnabled(cacheable=true)
    public static Account getAccount(Id recordId) {
        if (recordId == null) {
            return null;
        }

        SObjectAccessDecision securityDecision = Security.stripInaccessible(
            AccessType.READABLE,
            [
                SELECT
                    Name,
                    Description,
                    Website,
                    Parent.Name,
                    Facebook__c,
                    Meetup__c,
                    LinkedIn__c,
                    Parent.Website,
                    Parent.Parent.Name,
                    Parent.Parent.Website
                FROM Account
                WHERE Id = :recordId
            ]
        );

        return (Account) securityDecision.getRecords()[0];
    }

    // TODO: Come up with a logical/dynamic filter.
    @AuraEnabled(cacheable=true)
    public static List<Account> getAccounts() {
        if (!isAccountAccessible) {
            return new List<Account>();
        }

        return [SELECT Id, Name FROM Account];
    }

    @AuraEnabled(cacheable=true)
    public static List<Schedule__c> getUpcomingMeetings(Id accountId) {
        if (accountId == null || !isMeetingDateAccessible) {
            return new List<Schedule__c>();
        }

        return [
            SELECT Id, MeetingDate__c
            FROM Schedule__c
            WHERE Club__c = :accountId AND MeetingDate__c >= :System.today()
            ORDER BY MeetingDate__c DESC
        ];
    }
}