force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/MeetingDate__c.field-meta.xml
<CustomField>
    <fullName>MeetingDate__c</fullName>
    <label>Meeting Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ScheduleController_TEST.cls
@IsTest
private with sharing class ScheduleController_TEST {
    private static final Integer testSchedules = ScheduleController.LIMIT_TO + 1;

    @TestSetup
    private static void generateExistingData() {
        List<Schedule__c> schedules = new List<Schedule__c>();

        for (Integer i = 0; i < testSchedules; i++) {
            schedules.add(new Schedule__c(MeetingDate__c = System.today()));
        }

        insert schedules;
    }

    @IsTest
    private static void shouldReturnLimitedSchedules() {
        List<Schedule__c> schedules = ScheduleController.getSchedules();

        System.assertEquals(
            testSchedules - 1,
            schedules.size(),
            'Expected a limited number of schedules to be returned.'
        );
    }

    @IsTest
    private static void shouldReturnEmptyListWithoutAccess() {
        ScheduleController.isObjectAccessible = false;
        List<Schedule__c> schedules = ScheduleController.getSchedules();

        System.assertEquals(
            0,
            schedules.size(),
            'Did not expect schedules to return without object access'
        );
    }
}