force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/MeetingDate__c.field-meta.xml
<CustomField>
    <fullName>MeetingDate__c</fullName>
    <label>Meeting Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ScheduleController.cls
/*
 * Copyright (c) 2020, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class ScheduleController {
    @TestVisible
    private static final Integer LIMIT_TO = 25; //TODO: make this dynamic
    @TestVisible
    private static Boolean isObjectAccessible {
        get {
            if (isObjectAccessible == null) {
                isObjectAccessible = Schema.SObjectType.Schedule__c.isAccessible();
            }
            return isObjectAccessible;
        }
        set;
    }

    @AuraEnabled(cacheable=true)
    public static List<Schedule__c> getSchedules() {
        List<Schedule__c> schedules = new List<Schedule__c>();
        if (!isObjectAccessible) {
            return schedules;
        }

        return [SELECT Id FROM Schedule__c ORDER BY MeetingDate__c DESC LIMIT :LIMIT_TO];
    }
}